steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/udemy-course-447219/demo-flask-app:${_COMMIT_SHA}', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/udemy-course-447219/demo-flask-app:${_COMMIT_SHA}']

#- name: 'gcr.io/udemy-course-447219/demo-flask-app:${_COMMIT_SHA}'
#  entrypoint: 'bash'
#  args:
#   - '-c'
#   - |
#      cd /app && pytest
  
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args:
   - 'run'
   - 'deploy'
   - 'py-bq-load'
   - '--image'
   - 'gcr.io/udemy-course-447219/demo-flask-app:${_COMMIT_SHA}'
   - '--region'
   - 'us-central1'
   - '--allow-unauthenticated'
images:
- 'gcr.io/udemy-course-447219/demo-flask-app:${_COMMIT_SHA}'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _COMMIT_SHA: 'latest'  # You can replace 'latest' with your actual value if testing locally.